name: Build Release APK

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: |
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > local.properties
        echo "sdk.dir=/usr/local/lib/android/sdk" >> local.properties

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
        retention-days: 90
